from fastapi import APIRouter
from concurrent.futures import ThreadPoolExecutor, wait, FIRST_COMPLETED
from backend.schemas import ChatRequest, ChatResponse
from backend.services.recommendation_engine import get_recommendations
from backend.services.response_generator import generate_response

router = APIRouter()


@router.post("/chat", response_model=ChatResponse)
def chat(body: ChatRequest):
    """Process a user chat message and return hospital recommendations with
    a natural-language response generated by the Groq LLM.

    The recommendation pipeline and LLM response are run concurrently where
    possible to minimise total wall-clock latency.

    Body:
        message: User's symptom description
        lat: User latitude (defaults to central Bhubaneswar)
        lng: User longitude (defaults to central Bhubaneswar)
        top_n: Number of top hospitals to return (default 3)
    """
    # Step 1: Run get_recommendations (which internally parallelises OSRM + scoring)
    result = get_recommendations(body.message, body.lat, body.lng, body.top_n)

    # Step 2: Generate the LLM narrative response (Groq is fast — ~0.5s)
    llm_response = generate_response(result["classification"], result.get("recommendations", []))

    return {**result, "response": llm_response}
